name=vinamik-postgres-connector
connector.class=io.debezium.connector.postgresql.PostgresConnector

database.hostname=postgres
database.port=5432
database.user=postgres
database.password=1
database.dbname=vinamik_erp
database.server.name=vinamik_erp

topic.prefix=erp

plugin.name=pgoutput
publication.name=vinamik_erp_publication
slot.name=debezium_vinamik_slot
publication.autocreate.mode=filtered

table.include.list=public.transactions,public.general_ledger,public.accounts_receivable,public.accounts_payable,public.customers,public.vendors,public.cost_centers

transforms=route,unwrap
transforms.route.type=org.apache.kafka.connect.transforms.RegexRouter
transforms.route.regex=([^.]+)\\.([^.]+)\\.([^.]+)
transforms.route.replacement=$1.$3

transforms.unwrap.type=io.debezium.transforms.ExtractNewRecordState
transforms.unwrap.drop.tombstones=false
transforms.unwrap.delete.handling.mode=rewrite
transforms.unwrap.add.fields=op,table,ts_ms,source.ts_ms

tombstones.on.delete=false
snapshot.mode=initial
snapshot.isolation.mode=read_committed

decimal.handling.mode=double
time.precision.mode=adaptive
bigint.unsigned.handling.mode=long

max.batch.size=2048
max.queue.size=8192
poll.interval.ms=1000

errors.tolerance=all
errors.log.enable=true
errors.log.include.messages=true
